"""add rejection reason to driver profile

Revision ID: 65f73bdacb51
Revises: 2b0077bbf6e3
Create Date: 2026-06-19 15:22:29.138108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f73bdacb51'
down_revision: Union[str, Sequence[str], None] = '2b0077bbf6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_profiles', 'rejection_reason')
    # ### end Alembic commands ###
